/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables.records;


import appengine.parser.mysqlmodels.tables.Coinstatus;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoinstatusRecord extends TableRecordImpl<CoinstatusRecord> implements Record6<String, String, String, Timestamp, Byte, Byte> {

    private static final long serialVersionUID = 165060233;

    /**
     * Setter for <code>6txKRsiwk3.coinstatus.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.coinstatus.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>6txKRsiwk3.coinstatus.label</code>.
     */
    public void setLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.coinstatus.label</code>.
     */
    public String getLabel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>6txKRsiwk3.coinstatus.market</code>.
     */
    public void setMarket(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.coinstatus.market</code>.
     */
    public String getMarket() {
        return (String) get(2);
    }

    /**
     * Setter for <code>6txKRsiwk3.coinstatus.time</code>.
     */
    public void setTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.coinstatus.time</code>.
     */
    public Timestamp getTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>6txKRsiwk3.coinstatus.iswalletactive</code>.
     */
    public void setIswalletactive(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.coinstatus.iswalletactive</code>.
     */
    public Byte getIswalletactive() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>6txKRsiwk3.coinstatus.islistingactive</code>.
     */
    public void setIslistingactive(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.coinstatus.islistingactive</code>.
     */
    public Byte getIslistingactive() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Timestamp, Byte, Byte> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Timestamp, Byte, Byte> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Coinstatus.COINSTATUS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Coinstatus.COINSTATUS.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Coinstatus.COINSTATUS.MARKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Coinstatus.COINSTATUS.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Coinstatus.COINSTATUS.ISWALLETACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Coinstatus.COINSTATUS.ISLISTINGACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMarket();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIswalletactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIslistingactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinstatusRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinstatusRecord value2(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinstatusRecord value3(String value) {
        setMarket(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinstatusRecord value4(Timestamp value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinstatusRecord value5(Byte value) {
        setIswalletactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinstatusRecord value6(Byte value) {
        setIslistingactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinstatusRecord values(String value1, String value2, String value3, Timestamp value4, Byte value5, Byte value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoinstatusRecord
     */
    public CoinstatusRecord() {
        super(Coinstatus.COINSTATUS);
    }

    /**
     * Create a detached, initialised CoinstatusRecord
     */
    public CoinstatusRecord(String name, String label, String market, Timestamp time, Byte iswalletactive, Byte islistingactive) {
        super(Coinstatus.COINSTATUS);

        set(0, name);
        set(1, label);
        set(2, market);
        set(3, time);
        set(4, iswalletactive);
        set(5, islistingactive);
    }
}
