/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables.records;


import appengine.parser.mysqlmodels.enums.CointransferCurrentstate;
import appengine.parser.mysqlmodels.tables.Cointransfer;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CointransferRecord extends TableRecordImpl<CointransferRecord> implements Record14<String, Double, Double, Double, String, String, Double, Double, CointransferCurrentstate, Timestamp, String, String, Double, Double> {

    private static final long serialVersionUID = 1372099341;

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.coin</code>.
     */
    public void setCoin(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.coin</code>.
     */
    public String getCoin() {
        return (String) get(0);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.amount</code>.
     */
    public void setAmount(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.pricetobespentinbtc</code>.
     */
    public void setPricetobespentinbtc(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.pricetobespentinbtc</code>.
     */
    public Double getPricetobespentinbtc() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.profitestimatedinbtc</code>.
     */
    public void setProfitestimatedinbtc(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.profitestimatedinbtc</code>.
     */
    public Double getProfitestimatedinbtc() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.buymarket</code>.
     */
    public void setBuymarket(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.buymarket</code>.
     */
    public String getBuymarket() {
        return (String) get(4);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.sellmarket</code>.
     */
    public void setSellmarket(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.sellmarket</code>.
     */
    public String getSellmarket() {
        return (String) get(5);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.maxbuyprice</code>.
     */
    public void setMaxbuyprice(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.maxbuyprice</code>.
     */
    public Double getMaxbuyprice() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.minsellprice</code>.
     */
    public void setMinsellprice(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.minsellprice</code>.
     */
    public Double getMinsellprice() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.currentstate</code>.
     */
    public void setCurrentstate(CointransferCurrentstate value) {
        set(8, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.currentstate</code>.
     */
    public CointransferCurrentstate getCurrentstate() {
        return (CointransferCurrentstate) get(8);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.updatedtime</code>.
     */
    public void setUpdatedtime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.updatedtime</code>.
     */
    public Timestamp getUpdatedtime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.buyorderid</code>.
     */
    public void setBuyorderid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.buyorderid</code>.
     */
    public String getBuyorderid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.sellorderid</code>.
     */
    public void setSellorderid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.sellorderid</code>.
     */
    public String getSellorderid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.buyfilledamount</code>.
     */
    public void setBuyfilledamount(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.buyfilledamount</code>.
     */
    public Double getBuyfilledamount() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>6txKRsiwk3.cointransfer.sellfilledamount</code>.
     */
    public void setSellfilledamount(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.cointransfer.sellfilledamount</code>.
     */
    public Double getSellfilledamount() {
        return (Double) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, Double, Double, Double, String, String, Double, Double, CointransferCurrentstate, Timestamp, String, String, Double, Double> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, Double, Double, Double, String, String, Double, Double, CointransferCurrentstate, Timestamp, String, String, Double, Double> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Cointransfer.COINTRANSFER.COIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return Cointransfer.COINTRANSFER.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Cointransfer.COINTRANSFER.PRICETOBESPENTINBTC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Cointransfer.COINTRANSFER.PROFITESTIMATEDINBTC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Cointransfer.COINTRANSFER.BUYMARKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Cointransfer.COINTRANSFER.SELLMARKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Cointransfer.COINTRANSFER.MAXBUYPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return Cointransfer.COINTRANSFER.MINSELLPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<CointransferCurrentstate> field9() {
        return Cointransfer.COINTRANSFER.CURRENTSTATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Cointransfer.COINTRANSFER.UPDATEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Cointransfer.COINTRANSFER.BUYORDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Cointransfer.COINTRANSFER.SELLORDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return Cointransfer.COINTRANSFER.BUYFILLEDAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field14() {
        return Cointransfer.COINTRANSFER.SELLFILLEDAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCoin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getPricetobespentinbtc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getProfitestimatedinbtc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBuymarket();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSellmarket();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getMaxbuyprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getMinsellprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferCurrentstate value9() {
        return getCurrentstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getBuyorderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getSellorderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getBuyfilledamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value14() {
        return getSellfilledamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value1(String value) {
        setCoin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value2(Double value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value3(Double value) {
        setPricetobespentinbtc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value4(Double value) {
        setProfitestimatedinbtc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value5(String value) {
        setBuymarket(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value6(String value) {
        setSellmarket(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value7(Double value) {
        setMaxbuyprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value8(Double value) {
        setMinsellprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value9(CointransferCurrentstate value) {
        setCurrentstate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value10(Timestamp value) {
        setUpdatedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value11(String value) {
        setBuyorderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value12(String value) {
        setSellorderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value13(Double value) {
        setBuyfilledamount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord value14(Double value) {
        setSellfilledamount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CointransferRecord values(String value1, Double value2, Double value3, Double value4, String value5, String value6, Double value7, Double value8, CointransferCurrentstate value9, Timestamp value10, String value11, String value12, Double value13, Double value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CointransferRecord
     */
    public CointransferRecord() {
        super(Cointransfer.COINTRANSFER);
    }

    /**
     * Create a detached, initialised CointransferRecord
     */
    public CointransferRecord(String coin, Double amount, Double pricetobespentinbtc, Double profitestimatedinbtc, String buymarket, String sellmarket, Double maxbuyprice, Double minsellprice, CointransferCurrentstate currentstate, Timestamp updatedtime, String buyorderid, String sellorderid, Double buyfilledamount, Double sellfilledamount) {
        super(Cointransfer.COINTRANSFER);

        set(0, coin);
        set(1, amount);
        set(2, pricetobespentinbtc);
        set(3, profitestimatedinbtc);
        set(4, buymarket);
        set(5, sellmarket);
        set(6, maxbuyprice);
        set(7, minsellprice);
        set(8, currentstate);
        set(9, updatedtime);
        set(10, buyorderid);
        set(11, sellorderid);
        set(12, buyfilledamount);
        set(13, sellfilledamount);
    }
}
