/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables.records;


import appengine.parser.mysqlmodels.tables.Fromfbpage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FromfbpageRecord extends UpdatableRecordImpl<FromfbpageRecord> implements Record2<String, Timestamp> {

    private static final long serialVersionUID = -735197471;

    /**
     * Setter for <code>6txKRsiwk3.fromfbpage.from_page_id</code>.
     */
    public void setFromPageId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.fromfbpage.from_page_id</code>.
     */
    public String getFromPageId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>6txKRsiwk3.fromfbpage.updated_time</code>.
     */
    public void setUpdatedTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.fromfbpage.updated_time</code>.
     */
    public Timestamp getUpdatedTime() {
        return (Timestamp) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Fromfbpage.FROMFBPAGE.FROM_PAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Fromfbpage.FROMFBPAGE.UPDATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFromPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getUpdatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FromfbpageRecord value1(String value) {
        setFromPageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FromfbpageRecord value2(Timestamp value) {
        setUpdatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FromfbpageRecord values(String value1, Timestamp value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FromfbpageRecord
     */
    public FromfbpageRecord() {
        super(Fromfbpage.FROMFBPAGE);
    }

    /**
     * Create a detached, initialised FromfbpageRecord
     */
    public FromfbpageRecord(String fromPageId, Timestamp updatedTime) {
        super(Fromfbpage.FROMFBPAGE);

        set(0, fromPageId);
        set(1, updatedTime);
    }
}
