/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables.records;


import appengine.parser.mysqlmodels.tables.Instagramlastfetch;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstagramlastfetchRecord extends UpdatableRecordImpl<InstagramlastfetchRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -414297227;

    /**
     * Setter for <code>6txKRsiwk3.instagramlastfetch.pagename</code>.
     */
    public void setPagename(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.instagramlastfetch.pagename</code>.
     */
    public String getPagename() {
        return (String) get(0);
    }

    /**
     * Setter for <code>6txKRsiwk3.instagramlastfetch.lastcursor</code>.
     */
    public void setLastcursor(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.instagramlastfetch.lastcursor</code>.
     */
    public String getLastcursor() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Instagramlastfetch.INSTAGRAMLASTFETCH.PAGENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Instagramlastfetch.INSTAGRAMLASTFETCH.LASTCURSOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPagename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLastcursor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstagramlastfetchRecord value1(String value) {
        setPagename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstagramlastfetchRecord value2(String value) {
        setLastcursor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstagramlastfetchRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstagramlastfetchRecord
     */
    public InstagramlastfetchRecord() {
        super(Instagramlastfetch.INSTAGRAMLASTFETCH);
    }

    /**
     * Create a detached, initialised InstagramlastfetchRecord
     */
    public InstagramlastfetchRecord(String pagename, String lastcursor) {
        super(Instagramlastfetch.INSTAGRAMLASTFETCH);

        set(0, pagename);
        set(1, lastcursor);
    }
}
