/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables.records;


import appengine.parser.mysqlmodels.tables.Promotefbpage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PromotefbpageRecord extends UpdatableRecordImpl<PromotefbpageRecord> implements Record2<String, Timestamp> {

    private static final long serialVersionUID = -752736223;

    /**
     * Setter for <code>6txKRsiwk3.promotefbpage.fb_page_id</code>.
     */
    public void setFbPageId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.promotefbpage.fb_page_id</code>.
     */
    public String getFbPageId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>6txKRsiwk3.promotefbpage.updated_time</code>.
     */
    public void setUpdatedTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.promotefbpage.updated_time</code>.
     */
    public Timestamp getUpdatedTime() {
        return (Timestamp) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Promotefbpage.PROMOTEFBPAGE.FB_PAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Promotefbpage.PROMOTEFBPAGE.UPDATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFbPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getUpdatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromotefbpageRecord value1(String value) {
        setFbPageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromotefbpageRecord value2(Timestamp value) {
        setUpdatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PromotefbpageRecord values(String value1, Timestamp value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PromotefbpageRecord
     */
    public PromotefbpageRecord() {
        super(Promotefbpage.PROMOTEFBPAGE);
    }

    /**
     * Create a detached, initialised PromotefbpageRecord
     */
    public PromotefbpageRecord(String fbPageId, Timestamp updatedTime) {
        super(Promotefbpage.PROMOTEFBPAGE);

        set(0, fbPageId);
        set(1, updatedTime);
    }
}
