/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables.records;


import appengine.parser.mysqlmodels.tables.Twitterfollowers;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TwitterfollowersRecord extends UpdatableRecordImpl<TwitterfollowersRecord> implements Record11<Integer, String, String, String, Byte, Timestamp, String, Integer, Integer, Date, Integer> {

    private static final long serialVersionUID = 1219523340;

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.user_json</code>.
     */
    public void setUserJson(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.user_json</code>.
     */
    public String getUserJson() {
        return (String) get(2);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.follower_of</code>.
     */
    public void setFollowerOf(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.follower_of</code>.
     */
    public String getFollowerOf() {
        return (String) get(3);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.is_follow_request_sent</code>.
     */
    public void setIsFollowRequestSent(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.is_follow_request_sent</code>.
     */
    public Byte getIsFollowRequestSent() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.followedtime</code>.
     */
    public void setFollowedtime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.followedtime</code>.
     */
    public Timestamp getFollowedtime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.cursor</code>.
     */
    public void setCursor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.cursor</code>.
     */
    public String getCursor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.followersCount</code>.
     */
    public void setFollowerscount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.followersCount</code>.
     */
    public Integer getFollowerscount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.followingCount</code>.
     */
    public void setFollowingcount(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.followingCount</code>.
     */
    public Integer getFollowingcount() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.account_created_time</code>.
     */
    public void setAccountCreatedTime(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.account_created_time</code>.
     */
    public Date getAccountCreatedTime() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>6txKRsiwk3.twitterfollowers.statusesCount</code>.
     */
    public void setStatusescount(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.twitterfollowers.statusesCount</code>.
     */
    public Integer getStatusescount() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, Byte, Timestamp, String, Integer, Integer, Date, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, Byte, Timestamp, String, Integer, Integer, Date, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Twitterfollowers.TWITTERFOLLOWERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Twitterfollowers.TWITTERFOLLOWERS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Twitterfollowers.TWITTERFOLLOWERS.USER_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Twitterfollowers.TWITTERFOLLOWERS.FOLLOWER_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Twitterfollowers.TWITTERFOLLOWERS.IS_FOLLOW_REQUEST_SENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Twitterfollowers.TWITTERFOLLOWERS.FOLLOWEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Twitterfollowers.TWITTERFOLLOWERS.CURSOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Twitterfollowers.TWITTERFOLLOWERS.FOLLOWERSCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Twitterfollowers.TWITTERFOLLOWERS.FOLLOWINGCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field10() {
        return Twitterfollowers.TWITTERFOLLOWERS.ACCOUNT_CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Twitterfollowers.TWITTERFOLLOWERS.STATUSESCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFollowerOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsFollowRequestSent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getFollowedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCursor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getFollowerscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getFollowingcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value10() {
        return getAccountCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getStatusescount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value2(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value3(String value) {
        setUserJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value4(String value) {
        setFollowerOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value5(Byte value) {
        setIsFollowRequestSent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value6(Timestamp value) {
        setFollowedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value7(String value) {
        setCursor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value8(Integer value) {
        setFollowerscount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value9(Integer value) {
        setFollowingcount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value10(Date value) {
        setAccountCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord value11(Integer value) {
        setStatusescount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TwitterfollowersRecord values(Integer value1, String value2, String value3, String value4, Byte value5, Timestamp value6, String value7, Integer value8, Integer value9, Date value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwitterfollowersRecord
     */
    public TwitterfollowersRecord() {
        super(Twitterfollowers.TWITTERFOLLOWERS);
    }

    /**
     * Create a detached, initialised TwitterfollowersRecord
     */
    public TwitterfollowersRecord(Integer id, String userId, String userJson, String followerOf, Byte isFollowRequestSent, Timestamp followedtime, String cursor, Integer followerscount, Integer followingcount, Date accountCreatedTime, Integer statusescount) {
        super(Twitterfollowers.TWITTERFOLLOWERS);

        set(0, id);
        set(1, userId);
        set(2, userJson);
        set(3, followerOf);
        set(4, isFollowRequestSent);
        set(5, followedtime);
        set(6, cursor);
        set(7, followerscount);
        set(8, followingcount);
        set(9, accountCreatedTime);
        set(10, statusescount);
    }
}
