/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables.records;


import appengine.parser.mysqlmodels.tables.Weareswiggy;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeareswiggyRecord extends TableRecordImpl<WeareswiggyRecord> implements Record2<String, Byte> {

    private static final long serialVersionUID = -860177550;

    /**
     * Setter for <code>6txKRsiwk3.weareswiggy.lasttweet</code>.
     */
    public void setLasttweet(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.weareswiggy.lasttweet</code>.
     */
    public String getLasttweet() {
        return (String) get(0);
    }

    /**
     * Setter for <code>6txKRsiwk3.weareswiggy.isunique</code>.
     */
    public void setIsunique(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>6txKRsiwk3.weareswiggy.isunique</code>.
     */
    public Byte getIsunique() {
        return (Byte) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Byte> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Byte> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Weareswiggy.WEARESWIGGY.LASTTWEET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return Weareswiggy.WEARESWIGGY.ISUNIQUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLasttweet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getIsunique();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeareswiggyRecord value1(String value) {
        setLasttweet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeareswiggyRecord value2(Byte value) {
        setIsunique(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeareswiggyRecord values(String value1, Byte value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WeareswiggyRecord
     */
    public WeareswiggyRecord() {
        super(Weareswiggy.WEARESWIGGY);
    }

    /**
     * Create a detached, initialised WeareswiggyRecord
     */
    public WeareswiggyRecord(String lasttweet, Byte isunique) {
        super(Weareswiggy.WEARESWIGGY);

        set(0, lasttweet);
        set(1, isunique);
    }
}
