/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels;


import appengine.parser.mysqlmodels.tables.Coinprices;
import appengine.parser.mysqlmodels.tables.Coinstatus;
import appengine.parser.mysqlmodels.tables.Cointransfer;
import appengine.parser.mysqlmodels.tables.Fetcher;
import appengine.parser.mysqlmodels.tables.Fetcherhistory;
import appengine.parser.mysqlmodels.tables.Fromfbpage;
import appengine.parser.mysqlmodels.tables.FromfbpageTofbpage;
import appengine.parser.mysqlmodels.tables.GramUsers;
import appengine.parser.mysqlmodels.tables.Instagramfollowers;
import appengine.parser.mysqlmodels.tables.Instagramfollowersupdate;
import appengine.parser.mysqlmodels.tables.Instagramlastfetch;
import appengine.parser.mysqlmodels.tables.Instagramunfollowersupdate;
import appengine.parser.mysqlmodels.tables.Optimal;
import appengine.parser.mysqlmodels.tables.Optimaljson;
import appengine.parser.mysqlmodels.tables.Optimalnotify;
import appengine.parser.mysqlmodels.tables.Optimalupdate;
import appengine.parser.mysqlmodels.tables.Promotefbpage;
import appengine.parser.mysqlmodels.tables.Sockettradearbitary;
import appengine.parser.mysqlmodels.tables.Swiggyevents;
import appengine.parser.mysqlmodels.tables.Twitterfollowers;
import appengine.parser.mysqlmodels.tables.Ubereats;
import appengine.parser.mysqlmodels.tables.Weareswiggy;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 6txKRsiwk3
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>6txKRsiwk3.coinprices</code>.
     */
    public static final Coinprices COINPRICES = appengine.parser.mysqlmodels.tables.Coinprices.COINPRICES;

    /**
     * The table <code>6txKRsiwk3.coinstatus</code>.
     */
    public static final Coinstatus COINSTATUS = appengine.parser.mysqlmodels.tables.Coinstatus.COINSTATUS;

    /**
     * The table <code>6txKRsiwk3.cointransfer</code>.
     */
    public static final Cointransfer COINTRANSFER = appengine.parser.mysqlmodels.tables.Cointransfer.COINTRANSFER;

    /**
     * The table <code>6txKRsiwk3.fetcher</code>.
     */
    public static final Fetcher FETCHER = appengine.parser.mysqlmodels.tables.Fetcher.FETCHER;

    /**
     * The table <code>6txKRsiwk3.fetcherhistory</code>.
     */
    public static final Fetcherhistory FETCHERHISTORY = appengine.parser.mysqlmodels.tables.Fetcherhistory.FETCHERHISTORY;

    /**
     * The table <code>6txKRsiwk3.fromfbpage</code>.
     */
    public static final Fromfbpage FROMFBPAGE = appengine.parser.mysqlmodels.tables.Fromfbpage.FROMFBPAGE;

    /**
     * The table <code>6txKRsiwk3.fromfbpage_tofbpage</code>.
     */
    public static final FromfbpageTofbpage FROMFBPAGE_TOFBPAGE = appengine.parser.mysqlmodels.tables.FromfbpageTofbpage.FROMFBPAGE_TOFBPAGE;

    /**
     * The table <code>6txKRsiwk3.gram_users</code>.
     */
    public static final GramUsers GRAM_USERS = appengine.parser.mysqlmodels.tables.GramUsers.GRAM_USERS;

    /**
     * The table <code>6txKRsiwk3.instagramfollowers</code>.
     */
    public static final Instagramfollowers INSTAGRAMFOLLOWERS = appengine.parser.mysqlmodels.tables.Instagramfollowers.INSTAGRAMFOLLOWERS;

    /**
     * The table <code>6txKRsiwk3.instagramfollowersupdate</code>.
     */
    public static final Instagramfollowersupdate INSTAGRAMFOLLOWERSUPDATE = appengine.parser.mysqlmodels.tables.Instagramfollowersupdate.INSTAGRAMFOLLOWERSUPDATE;

    /**
     * The table <code>6txKRsiwk3.instagramlastfetch</code>.
     */
    public static final Instagramlastfetch INSTAGRAMLASTFETCH = appengine.parser.mysqlmodels.tables.Instagramlastfetch.INSTAGRAMLASTFETCH;

    /**
     * The table <code>6txKRsiwk3.instagramunfollowersupdate</code>.
     */
    public static final Instagramunfollowersupdate INSTAGRAMUNFOLLOWERSUPDATE = appengine.parser.mysqlmodels.tables.Instagramunfollowersupdate.INSTAGRAMUNFOLLOWERSUPDATE;

    /**
     * The table <code>6txKRsiwk3.optimal</code>.
     */
    public static final Optimal OPTIMAL = appengine.parser.mysqlmodels.tables.Optimal.OPTIMAL;

    /**
     * The table <code>6txKRsiwk3.optimaljson</code>.
     */
    public static final Optimaljson OPTIMALJSON = appengine.parser.mysqlmodels.tables.Optimaljson.OPTIMALJSON;

    /**
     * The table <code>6txKRsiwk3.optimalnotify</code>.
     */
    public static final Optimalnotify OPTIMALNOTIFY = appengine.parser.mysqlmodels.tables.Optimalnotify.OPTIMALNOTIFY;

    /**
     * The table <code>6txKRsiwk3.optimalupdate</code>.
     */
    public static final Optimalupdate OPTIMALUPDATE = appengine.parser.mysqlmodels.tables.Optimalupdate.OPTIMALUPDATE;

    /**
     * The table <code>6txKRsiwk3.promotefbpage</code>.
     */
    public static final Promotefbpage PROMOTEFBPAGE = appengine.parser.mysqlmodels.tables.Promotefbpage.PROMOTEFBPAGE;

    /**
     * The table <code>6txKRsiwk3.sockettradearbitary</code>.
     */
    public static final Sockettradearbitary SOCKETTRADEARBITARY = appengine.parser.mysqlmodels.tables.Sockettradearbitary.SOCKETTRADEARBITARY;

    /**
     * The table <code>6txKRsiwk3.swiggyevents</code>.
     */
    public static final Swiggyevents SWIGGYEVENTS = appengine.parser.mysqlmodels.tables.Swiggyevents.SWIGGYEVENTS;

    /**
     * The table <code>6txKRsiwk3.twitterfollowers</code>.
     */
    public static final Twitterfollowers TWITTERFOLLOWERS = appengine.parser.mysqlmodels.tables.Twitterfollowers.TWITTERFOLLOWERS;

    /**
     * The table <code>6txKRsiwk3.ubereats</code>.
     */
    public static final Ubereats UBEREATS = appengine.parser.mysqlmodels.tables.Ubereats.UBEREATS;

    /**
     * The table <code>6txKRsiwk3.weareswiggy</code>.
     */
    public static final Weareswiggy WEARESWIGGY = appengine.parser.mysqlmodels.tables.Weareswiggy.WEARESWIGGY;
}
