/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels.Keys;
import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.CoinstatusRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Coinstatus extends TableImpl<CoinstatusRecord> {

    private static final long serialVersionUID = 1030769799;

    /**
     * The reference instance of <code>6txKRsiwk3.coinstatus</code>
     */
    public static final Coinstatus COINSTATUS = new Coinstatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoinstatusRecord> getRecordType() {
        return CoinstatusRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.coinstatus.name</code>.
     */
    public final TableField<CoinstatusRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * The column <code>6txKRsiwk3.coinstatus.label</code>.
     */
    public final TableField<CoinstatusRecord, String> LABEL = createField("label", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>6txKRsiwk3.coinstatus.market</code>.
     */
    public final TableField<CoinstatusRecord, String> MARKET = createField("market", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * The column <code>6txKRsiwk3.coinstatus.time</code>.
     */
    public final TableField<CoinstatusRecord, Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>6txKRsiwk3.coinstatus.iswalletactive</code>.
     */
    public final TableField<CoinstatusRecord, Byte> ISWALLETACTIVE = createField("iswalletactive", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>6txKRsiwk3.coinstatus.islistingactive</code>.
     */
    public final TableField<CoinstatusRecord, Byte> ISLISTINGACTIVE = createField("islistingactive", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * Create a <code>6txKRsiwk3.coinstatus</code> table reference
     */
    public Coinstatus() {
        this("coinstatus", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.coinstatus</code> table reference
     */
    public Coinstatus(String alias) {
        this(alias, COINSTATUS);
    }

    private Coinstatus(String alias, Table<CoinstatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private Coinstatus(String alias, Table<CoinstatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CoinstatusRecord>> getKeys() {
        return Arrays.<UniqueKey<CoinstatusRecord>>asList(Keys.KEY_COINSTATUS_COINSTATUS_LABEL_MARKET_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Coinstatus as(String alias) {
        return new Coinstatus(alias, this);
    }

    /**
     * Rename this table
     */
    public Coinstatus rename(String name) {
        return new Coinstatus(name, null);
    }
}
