/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels.Keys;
import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.FromfbpageTofbpageRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FromfbpageTofbpage extends TableImpl<FromfbpageTofbpageRecord> {

    private static final long serialVersionUID = -346680557;

    /**
     * The reference instance of <code>6txKRsiwk3.fromfbpage_tofbpage</code>
     */
    public static final FromfbpageTofbpage FROMFBPAGE_TOFBPAGE = new FromfbpageTofbpage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FromfbpageTofbpageRecord> getRecordType() {
        return FromfbpageTofbpageRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.fromfbpage_tofbpage.from_page_id</code>.
     */
    public final TableField<FromfbpageTofbpageRecord, String> FROM_PAGE_ID = createField("from_page_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.fromfbpage_tofbpage.to_page_id</code>.
     */
    public final TableField<FromfbpageTofbpageRecord, String> TO_PAGE_ID = createField("to_page_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.fromfbpage_tofbpage.updated_time</code>.
     */
    public final TableField<FromfbpageTofbpageRecord, Timestamp> UPDATED_TIME = createField("updated_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>6txKRsiwk3.fromfbpage_tofbpage</code> table reference
     */
    public FromfbpageTofbpage() {
        this("fromfbpage_tofbpage", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.fromfbpage_tofbpage</code> table reference
     */
    public FromfbpageTofbpage(String alias) {
        this(alias, FROMFBPAGE_TOFBPAGE);
    }

    private FromfbpageTofbpage(String alias, Table<FromfbpageTofbpageRecord> aliased) {
        this(alias, aliased, null);
    }

    private FromfbpageTofbpage(String alias, Table<FromfbpageTofbpageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FromfbpageTofbpageRecord> getPrimaryKey() {
        return Keys.KEY_FROMFBPAGE_TOFBPAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FromfbpageTofbpageRecord>> getKeys() {
        return Arrays.<UniqueKey<FromfbpageTofbpageRecord>>asList(Keys.KEY_FROMFBPAGE_TOFBPAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FromfbpageTofbpage as(String alias) {
        return new FromfbpageTofbpage(alias, this);
    }

    /**
     * Rename this table
     */
    public FromfbpageTofbpage rename(String name) {
        return new FromfbpageTofbpage(name, null);
    }
}
