/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels.Keys;
import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.FromfbpageRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fromfbpage extends TableImpl<FromfbpageRecord> {

    private static final long serialVersionUID = -1963033080;

    /**
     * The reference instance of <code>6txKRsiwk3.fromfbpage</code>
     */
    public static final Fromfbpage FROMFBPAGE = new Fromfbpage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FromfbpageRecord> getRecordType() {
        return FromfbpageRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.fromfbpage.from_page_id</code>.
     */
    public final TableField<FromfbpageRecord, String> FROM_PAGE_ID = createField("from_page_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.fromfbpage.updated_time</code>.
     */
    public final TableField<FromfbpageRecord, Timestamp> UPDATED_TIME = createField("updated_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>6txKRsiwk3.fromfbpage</code> table reference
     */
    public Fromfbpage() {
        this("fromfbpage", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.fromfbpage</code> table reference
     */
    public Fromfbpage(String alias) {
        this(alias, FROMFBPAGE);
    }

    private Fromfbpage(String alias, Table<FromfbpageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Fromfbpage(String alias, Table<FromfbpageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FromfbpageRecord> getPrimaryKey() {
        return Keys.KEY_FROMFBPAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FromfbpageRecord>> getKeys() {
        return Arrays.<UniqueKey<FromfbpageRecord>>asList(Keys.KEY_FROMFBPAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Fromfbpage as(String alias) {
        return new Fromfbpage(alias, this);
    }

    /**
     * Rename this table
     */
    public Fromfbpage rename(String name) {
        return new Fromfbpage(name, null);
    }
}
