/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.GramUsersRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GramUsers extends TableImpl<GramUsersRecord> {

    private static final long serialVersionUID = -1194012100;

    /**
     * The reference instance of <code>6txKRsiwk3.gram_users</code>
     */
    public static final GramUsers GRAM_USERS = new GramUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GramUsersRecord> getRecordType() {
        return GramUsersRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.gram_users.id</code>.
     */
    public final TableField<GramUsersRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * The column <code>6txKRsiwk3.gram_users.username</code>.
     */
    public final TableField<GramUsersRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>6txKRsiwk3.gram_users.mediacount</code>.
     */
    public final TableField<GramUsersRecord, Integer> MEDIACOUNT = createField("mediacount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>6txKRsiwk3.gram_users.followercount</code>.
     */
    public final TableField<GramUsersRecord, Integer> FOLLOWERCOUNT = createField("followercount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>6txKRsiwk3.gram_users.followingcount</code>.
     */
    public final TableField<GramUsersRecord, Integer> FOLLOWINGCOUNT = createField("followingcount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>6txKRsiwk3.gram_users.credittake</code>.
     */
    public final TableField<GramUsersRecord, Integer> CREDITTAKE = createField("credittake", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>6txKRsiwk3.gram_users</code> table reference
     */
    public GramUsers() {
        this("gram_users", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.gram_users</code> table reference
     */
    public GramUsers(String alias) {
        this(alias, GRAM_USERS);
    }

    private GramUsers(String alias, Table<GramUsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private GramUsers(String alias, Table<GramUsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GramUsers as(String alias) {
        return new GramUsers(alias, this);
    }

    /**
     * Rename this table
     */
    public GramUsers rename(String name) {
        return new GramUsers(name, null);
    }
}
