/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels.Keys;
import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.InstagramlastfetchRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Instagramlastfetch extends TableImpl<InstagramlastfetchRecord> {

    private static final long serialVersionUID = 427309561;

    /**
     * The reference instance of <code>6txKRsiwk3.instagramlastfetch</code>
     */
    public static final Instagramlastfetch INSTAGRAMLASTFETCH = new Instagramlastfetch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstagramlastfetchRecord> getRecordType() {
        return InstagramlastfetchRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.instagramlastfetch.pagename</code>.
     */
    public final TableField<InstagramlastfetchRecord, String> PAGENAME = createField("pagename", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.instagramlastfetch.lastcursor</code>.
     */
    public final TableField<InstagramlastfetchRecord, String> LASTCURSOR = createField("lastcursor", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

    /**
     * Create a <code>6txKRsiwk3.instagramlastfetch</code> table reference
     */
    public Instagramlastfetch() {
        this("instagramlastfetch", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.instagramlastfetch</code> table reference
     */
    public Instagramlastfetch(String alias) {
        this(alias, INSTAGRAMLASTFETCH);
    }

    private Instagramlastfetch(String alias, Table<InstagramlastfetchRecord> aliased) {
        this(alias, aliased, null);
    }

    private Instagramlastfetch(String alias, Table<InstagramlastfetchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InstagramlastfetchRecord> getPrimaryKey() {
        return Keys.KEY_INSTAGRAMLASTFETCH_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InstagramlastfetchRecord>> getKeys() {
        return Arrays.<UniqueKey<InstagramlastfetchRecord>>asList(Keys.KEY_INSTAGRAMLASTFETCH_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Instagramlastfetch as(String alias) {
        return new Instagramlastfetch(alias, this);
    }

    /**
     * Rename this table
     */
    public Instagramlastfetch rename(String name) {
        return new Instagramlastfetch(name, null);
    }
}
