/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels.Keys;
import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.InstagramfollowersupdateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Instagramfollowersupdate extends TableImpl<InstagramfollowersupdateRecord> {

    private static final long serialVersionUID = 1638806038;

    /**
     * The reference instance of <code>6txKRsiwk3.instagramfollowersupdate</code>
     */
    public static final Instagramfollowersupdate INSTAGRAMFOLLOWERSUPDATE = new Instagramfollowersupdate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstagramfollowersupdateRecord> getRecordType() {
        return InstagramfollowersupdateRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.instagramfollowersupdate.pagename</code>.
     */
    public final TableField<InstagramfollowersupdateRecord, String> PAGENAME = createField("pagename", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.instagramfollowersupdate.from_user_name</code>.
     */
    public final TableField<InstagramfollowersupdateRecord, String> FROM_USER_NAME = createField("from_user_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.instagramfollowersupdate.followed_till</code>.
     */
    public final TableField<InstagramfollowersupdateRecord, Integer> FOLLOWED_TILL = createField("followed_till", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>6txKRsiwk3.instagramfollowersupdate</code> table reference
     */
    public Instagramfollowersupdate() {
        this("instagramfollowersupdate", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.instagramfollowersupdate</code> table reference
     */
    public Instagramfollowersupdate(String alias) {
        this(alias, INSTAGRAMFOLLOWERSUPDATE);
    }

    private Instagramfollowersupdate(String alias, Table<InstagramfollowersupdateRecord> aliased) {
        this(alias, aliased, null);
    }

    private Instagramfollowersupdate(String alias, Table<InstagramfollowersupdateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InstagramfollowersupdateRecord> getPrimaryKey() {
        return Keys.KEY_INSTAGRAMFOLLOWERSUPDATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InstagramfollowersupdateRecord>> getKeys() {
        return Arrays.<UniqueKey<InstagramfollowersupdateRecord>>asList(Keys.KEY_INSTAGRAMFOLLOWERSUPDATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Instagramfollowersupdate as(String alias) {
        return new Instagramfollowersupdate(alias, this);
    }

    /**
     * Rename this table
     */
    public Instagramfollowersupdate rename(String name) {
        return new Instagramfollowersupdate(name, null);
    }
}
