/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.OptimaljsonRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Optimaljson extends TableImpl<OptimaljsonRecord> {

    private static final long serialVersionUID = 2120264113;

    /**
     * The reference instance of <code>6txKRsiwk3.optimaljson</code>
     */
    public static final Optimaljson OPTIMALJSON = new Optimaljson();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OptimaljsonRecord> getRecordType() {
        return OptimaljsonRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.optimaljson.time</code>.
     */
    public final TableField<OptimaljsonRecord, Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>6txKRsiwk3.optimaljson.json</code>.
     */
    public final TableField<OptimaljsonRecord, String> JSON = createField("json", org.jooq.impl.SQLDataType.VARCHAR.length(5000), this, "");

    /**
     * The column <code>6txKRsiwk3.optimaljson.coinlabel</code>.
     */
    public final TableField<OptimaljsonRecord, String> COINLABEL = createField("coinlabel", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * Create a <code>6txKRsiwk3.optimaljson</code> table reference
     */
    public Optimaljson() {
        this("optimaljson", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.optimaljson</code> table reference
     */
    public Optimaljson(String alias) {
        this(alias, OPTIMALJSON);
    }

    private Optimaljson(String alias, Table<OptimaljsonRecord> aliased) {
        this(alias, aliased, null);
    }

    private Optimaljson(String alias, Table<OptimaljsonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optimaljson as(String alias) {
        return new Optimaljson(alias, this);
    }

    /**
     * Rename this table
     */
    public Optimaljson rename(String name) {
        return new Optimaljson(name, null);
    }
}
