/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels.Keys;
import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.TwitterfollowersRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Twitterfollowers extends TableImpl<TwitterfollowersRecord> {

    private static final long serialVersionUID = 45272585;

    /**
     * The reference instance of <code>6txKRsiwk3.twitterfollowers</code>
     */
    public static final Twitterfollowers TWITTERFOLLOWERS = new Twitterfollowers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TwitterfollowersRecord> getRecordType() {
        return TwitterfollowersRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.id</code>.
     */
    public final TableField<TwitterfollowersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.user_id</code>.
     */
    public final TableField<TwitterfollowersRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.user_json</code>.
     */
    public final TableField<TwitterfollowersRecord, String> USER_JSON = createField("user_json", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.follower_of</code>.
     */
    public final TableField<TwitterfollowersRecord, String> FOLLOWER_OF = createField("follower_of", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.is_follow_request_sent</code>.
     */
    public final TableField<TwitterfollowersRecord, Byte> IS_FOLLOW_REQUEST_SENT = createField("is_follow_request_sent", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.followedtime</code>.
     */
    public final TableField<TwitterfollowersRecord, Timestamp> FOLLOWEDTIME = createField("followedtime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.cursor</code>.
     */
    public final TableField<TwitterfollowersRecord, String> CURSOR = createField("cursor", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.followersCount</code>.
     */
    public final TableField<TwitterfollowersRecord, Integer> FOLLOWERSCOUNT = createField("followersCount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.followingCount</code>.
     */
    public final TableField<TwitterfollowersRecord, Integer> FOLLOWINGCOUNT = createField("followingCount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.account_created_time</code>.
     */
    public final TableField<TwitterfollowersRecord, Date> ACCOUNT_CREATED_TIME = createField("account_created_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>6txKRsiwk3.twitterfollowers.statusesCount</code>.
     */
    public final TableField<TwitterfollowersRecord, Integer> STATUSESCOUNT = createField("statusesCount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>6txKRsiwk3.twitterfollowers</code> table reference
     */
    public Twitterfollowers() {
        this("twitterfollowers", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.twitterfollowers</code> table reference
     */
    public Twitterfollowers(String alias) {
        this(alias, TWITTERFOLLOWERS);
    }

    private Twitterfollowers(String alias, Table<TwitterfollowersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Twitterfollowers(String alias, Table<TwitterfollowersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TwitterfollowersRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TWITTERFOLLOWERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TwitterfollowersRecord> getPrimaryKey() {
        return Keys.KEY_TWITTERFOLLOWERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TwitterfollowersRecord>> getKeys() {
        return Arrays.<UniqueKey<TwitterfollowersRecord>>asList(Keys.KEY_TWITTERFOLLOWERS_PRIMARY, Keys.KEY_TWITTERFOLLOWERS_TWITTERFOLLOWERS_USER_ID_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Twitterfollowers as(String alias) {
        return new Twitterfollowers(alias, this);
    }

    /**
     * Rename this table
     */
    public Twitterfollowers rename(String name) {
        return new Twitterfollowers(name, null);
    }
}
