/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels.Keys;
import appengine.parser.mysqlmodels._6txkrsiwk3;
import appengine.parser.mysqlmodels.tables.records.WeareswiggyRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Weareswiggy extends TableImpl<WeareswiggyRecord> {

    private static final long serialVersionUID = -2083387007;

    /**
     * The reference instance of <code>6txKRsiwk3.weareswiggy</code>
     */
    public static final Weareswiggy WEARESWIGGY = new Weareswiggy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WeareswiggyRecord> getRecordType() {
        return WeareswiggyRecord.class;
    }

    /**
     * The column <code>6txKRsiwk3.weareswiggy.lasttweet</code>.
     */
    public final TableField<WeareswiggyRecord, String> LASTTWEET = createField("lasttweet", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>6txKRsiwk3.weareswiggy.isunique</code>.
     */
    public final TableField<WeareswiggyRecord, Byte> ISUNIQUE = createField("isunique", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>6txKRsiwk3.weareswiggy</code> table reference
     */
    public Weareswiggy() {
        this("weareswiggy", null);
    }

    /**
     * Create an aliased <code>6txKRsiwk3.weareswiggy</code> table reference
     */
    public Weareswiggy(String alias) {
        this(alias, WEARESWIGGY);
    }

    private Weareswiggy(String alias, Table<WeareswiggyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Weareswiggy(String alias, Table<WeareswiggyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return _6txkrsiwk3._6TXKRSIWK3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WeareswiggyRecord>> getKeys() {
        return Arrays.<UniqueKey<WeareswiggyRecord>>asList(Keys.KEY_WEARESWIGGY_WEARESWIGGY_ISUNIQUE_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Weareswiggy as(String alias) {
        return new Weareswiggy(alias, this);
    }

    /**
     * Rename this table
     */
    public Weareswiggy rename(String name) {
        return new Weareswiggy(name, null);
    }
}
