/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.enums;


import javax.annotation.Generated;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CointransferCurrentstate implements EnumType {

    PURCHASED("PURCHASED"),

    WITHDRAWL_PENDING("WITHDRAWL_PENDING"),

    WITHDRAWL("WITHDRAWL"),

    DEPOSIT_PENDING("DEPOSIT_PENDING"),

    DEPOSIT("DEPOSIT"),

    SOLD("SOLD");

    private final String literal;

    private CointransferCurrentstate(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "cointransfer_currentstate";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
