/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.enums;


import javax.annotation.Generated;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum OptimalnotifyNotifytype implements EnumType {

    NEWRAISE("NEWRAISE"),

    RAISEINCREASE("RAISEINCREASE"),

    RAISEDECREASE("RAISEDECREASE"),

    EQUAL("EQUAL"),

    LOSS("LOSS");

    private final String literal;

    private OptimalnotifyNotifytype(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "optimalnotify_notifytype";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
